### ISSUE TITLE
Ajout du smiley bounce en .SVG

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/documents-communication#14]
![](https://i.imgur.com/UscfGea.gif)

Pour le svg j'ai pris :
 - la bouche de : ![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/master/emoticones/clemojiv3/svg/heureux.svg?sanitize=true) ou on peut prendre celle de :lol: ou celle modifier ci-dessous ;
 - les yeux de ![](https://raw.githubusercontent.com/zestedesavoir/documents-communication/master/emoticones/clemojiv3/svg/hihi.svg?sanitize=true) ;

qu'on trouve ici : https://github.com/zestedesavoir/documents-communication/tree/master/emoticones/clemoji#emoji-v2-to-clemoji-v3-

----

Ce qu'il faut gérer le mouvement de la bouche et des yeux via du js, et cacher/afficher les feuilles selon l'étape de l'animation

![sprites](https://user-images.githubusercontent.com/18501150/48554455-c2008d80-e8de-11e8-9012-9e23188c9e32.png)

```css
.clem_happy_bounce_000.png{width:29px;height:38px;background: url("sprites.png") no-repeat -58px -0px;}
.clem_happy_bounce_001.png{width:29px;height:38px;background: url("sprites.png") no-repeat -0px -38px;}
.clem_happy_bounce_002.png{width:29px;height:38px;background: url("sprites.png") no-repeat -29px -0px;}
.clem_happy_bounce_003.png{width:29px;height:38px;background: url("sprites.png") no-repeat -0px -0px;}
.clem_happy_bounce_004.png{width:29px;height:38px;background: url("sprites.png") no-repeat -29px -38px;}
.clem_happy_bounce_005.png{width:29px;height:38px;background: url("sprites.png") no-repeat -58px -38px;}
```

## Bounce

![clem_happy_bounce.gif](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/clem_happy_bounce.gif)

| Step | SVG             | 
| ---- | --------------- | 
| 1    | ![1.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/1.svg?sanitize=true) | 
| 2    | ![2.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/2.svg?sanitize=true) | 
| 3    | ![3.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/3.svg?sanitize=true) | 
| 4    | ![4.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/4.svg?sanitize=true) | 
| 5    | ![5.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/5.svg?sanitize=true) | 
| 6    | ![6.svg](https://raw.githubusercontent.com/A-312/documents-communication/bounce/emoticones/clemoji/bounce/6.svg?sanitize=true) | 

https://github.com/A-312/documents-communication/tree/bounce/emoticones/clemoji/bounce
